=== grupo1edix1/ae2lm/biblioteca/biblioteca.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="biblioteca">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="libro" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="titulo">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:minLength value="1"></xs:minLength>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="capitulos" minOccurs="0">
                            <xs:complexType>
                                <xs:sequence>                                                             
                                    <xs:element name="capitulo" minOccurs="0" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:simpleContent>
                                                <xs:extension base="xs:string">
                                                    <xs:attribute name="pag" type="xs:positiveInteger"></xs:attribute>                 
                                                </xs:extension>
                                            </xs:simpleContent>
                                        </xs:complexType>                                       
                                    </xs:element>                                                                                                                                                                    
                                </xs:sequence>                                  
                            </xs:complexType>                            
                        </xs:element>
                        <xs:element name="indice" type="xs:string" minOccurs="0"></xs:element>
                        <xs:element name="sinopsis" type="xs:string" minOccurs="0"></xs:element>
                    </xs:sequence>
                    <xs:attribute name="id" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:length value="5"></xs:length>
                                <xs:pattern value="L[0-9]{4}"></xs:pattern>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="tipo_clase" use="optional" default="novela">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="novela"></xs:enumeration>
                                <xs:enumeration value="infantil"></xs:enumeration>
                                <xs:enumeration value="didactico"></xs:enumeration>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="pag">
                        <xs:simpleType>
                            <xs:restriction base="xs:integer">
                                <xs:minInclusive value="1"></xs:minInclusive>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:complexType>               
            </xs:element>                    

            <xs:element name="revista" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                <xs:documentation>esto es un Ã±ordo</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="titulo">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:minLength value="1"></xs:minLength>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="numero" type="xs:integer" minOccurs="1"></xs:element>
                        <xs:element name="indice" type="xs:string" minOccurs="0"></xs:element>
                        <xs:element name="secciones" minOccurs="0">
                            <xs:complexType>
                                <xs:sequence>                                                             
                                    <xs:element name="seccion" minOccurs="0" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:simpleContent>
                                                <xs:extension base="xs:string">
                                                    <xs:attribute name="pag" type="xs:positiveInteger"></xs:attribute>                 
                                                </xs:extension>
                                            </xs:simpleContent>
                                        </xs:complexType>                                       
                                    </xs:element>                                                                                                                                                                    
                                </xs:sequence>                                  
                            </xs:complexType>              
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="id" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:length value="5"></xs:length>
                                <xs:pattern value="R[0-9]{4}"></xs:pattern>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="tipo_clase" default="otros">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="informatica"></xs:enumeration>
                                <xs:enumeration value="corazon"></xs:enumeration>
                                <xs:enumeration value="coches"></xs:enumeration>
                                <xs:enumeration value="investigacion"></xs:enumeration>
                                <xs:enumeration value="otros"></xs:enumeration>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:complexType>               
            </xs:element>
            
            <xs:element name="periodico" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="titulo">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:minLength value="1"></xs:minLength>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="fecha" type="xs:date" minOccurs="0">
                        </xs:element>
                        <xs:element name="indice" minOccurs="0"></xs:element>
                        <xs:element name="secciones" minOccurs="0">
                            <xs:complexType>
                                <xs:sequence>                                                             
                                    <xs:element name="seccion" minOccurs="0" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:simpleContent>
                                                <xs:extension base="xs:string">
                                                    <xs:attribute name="pag" type="xs:positiveInteger"></xs:attribute>                 
                                                </xs:extension>
                                            </xs:simpleContent>
                                        </xs:complexType>                                       
                                    </xs:element>                                                                                                                                                                    
                                </xs:sequence>                                  
                            </xs:complexType>         
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="id" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:length value="5"></xs:length>
                                <xs:pattern value="P[0-9]{4}"></xs:pattern>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="tipo_clase" default="internacional">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="nacional"></xs:enumeration>
                                <xs:enumeration value="internacional"></xs:enumeration>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="fecha" type="xs:date" use="optional"></xs:attribute>
                </xs:complexType>               
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== grupo1edix1/ae2lm/biblioteca/biblioteca_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation= "biblioteca.xsd">

    <libro id="L4897">
        <titulo>Popopo</titulo>
        <capitulos>
            <capitulo pag="1">Ppopopo</capitulo>
        </capitulos>
        <sinopsis>Es la crema</sinopsis>  
    </libro>

    <libro id="L1561">
        <titulo>Guardi√°n sobre el centeno</titulo>
    </libro>

    <periodico id="P1598">
        <titulo>Washington Post</titulo>
        <fecha>2020-03-12</fecha>
        <indice>
            1- Noticiario
            2- Coloquio
            3- Deportes
        </indice>
        <secciones>
            <seccion pag="165">Noticiario</seccion>
            <seccion pag="15">Esquelas</seccion>
            <seccion pag="12">Wokismo</seccion>
        </secciones>        
    </periodico>
    
</biblioteca>
