=== grupo1edix1/ae2lm/biblioteca/biblioteca.dtd
<!ELEMENT biblioteca (libro|revista|periodico)*>
        <!ELEMENT libro  (titulo, capitulos?, indice?, sinopsis?)>
            <!ATTLIST libro id ID #REQUIRED>
            <!ATTLIST libro tipo_clase (novela|infantil|didactico) "novela">
            <!ATTLIST libro pag CDATA #IMPLIED>
                  
        <!ELEMENT revista (titulo, numero, indice?, secciones?)>
            <!ATTLIST revista id ID #REQUIRED>
            <!ATTLIST revista tipo_clase (informatica|corazon|coches|investigacion|otros) "informatica">
            <!ATTLIST revista pag CDATA #IMPLIED>

        <!ELEMENT periodico (titulo, indice?, seccionesP?)>
            <!ATTLIST periodico id ID #REQUIRED>
            <!ATTLIST periodico tipo_clase (internacional|nacional) "internacional">
            <!ATTLIST periodico fecha CDATA #IMPLIED>    
      
        <!ELEMENT titulo (#PCDATA)>
        <!ELEMENT numero (#PCDATA)>
        <!ELEMENT indice (#PCDATA)>
        <!ELEMENT sinopsis (#PCDATA)>       
        <!ELEMENT capitulos (capitulo)+>
            <!ELEMENT capitulo (contenido)>
                <!ATTLIST capitulo num NMTOKEN #REQUIRED>
                <!ATTLIST capitulo pag CDATA #IMPLIED>
            <!ELEMENT contenido (#PCDATA)>
                <!ATTLIST contenido info CDATA #IMPLIED>    
        <!ELEMENT secciones (seccion)*>
            <!ELEMENT seccion (contenido)> 
                <!ATTLIST seccion pag CDATA #IMPLIED>
        <!ELEMENT seccionesP (seccionP)*>
            <!ELEMENT seccionP (articulo)*> 
                <!ATTLIST seccionP tipo (economia|opinion|deporte|nacional|internacional) "nacional">
            <!ELEMENT articulo (contenido)> 
                <!ATTLIST articulo autor CDATA #IMPLIED>

=== grupo1edix1/ae2lm/biblioteca/biblioteca_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">

<biblioteca>
    <libro id="L4897" tipo_clase="novela">
        <titulo>La Divina Comedia</titulo>
        <capitulos>
            <capitulo num="1" pag="10"><contenido>Infierno</contenido></capitulo>
            <capitulo num="2" pag="50"><contenido>Purgatorio</contenido> </capitulo>
            <capitulo num="3" pag="110"><contenido>Paraíso</contenido></capitulo>
        </capitulos>
        <sinopsis>Dante viaja con Virgilio al Infierno</sinopsis>  
    </libro>

    <libro id="L4987">
        <titulo>Guardián sobre el centeno</titulo>
    </libro>

    <revista id="R1568">
        <titulo>ARTE</titulo>
        <numero>15</numero>
    </revista>

    <revista id="R1569">
        <titulo>ARTE</titulo>
        <numero>16</numero>
        <secciones>
            <seccion pag="54"> Otto Dix</seccion>
            <seccion>Hockney</seccion>        
        </secciones>
    </revista>

    <periodico id="P1598" fecha="2020-03-12">
        <titulo>Washington Post</titulo>
        <indice>
            1- Noticiario
            2- Coloquio
            3- Deportes
        </indice>
        <seccionesP>
            <seccionP tipo="nacional"><articulo autor="Prada"><contenido> Mucho texto</contenido></articulo></seccionP>
        </seccionesP> 
    </periodico>
</biblioteca>
